### ISSUE TITLE
Change the UI according to the new design

### ISSUE THREAD

**Issue by coderwassananmol** [coderwassananmol/BUB2#78] opened 2020-03-11 17:22 UTC
A .fig file resides insides public folder. New UI has to be made in accordance with that.

**Comment by poojasrinivass** [comment] 2020-03-11 20:06
I would like to work on this isuue

**Comment by coderwassananmol** [comment] 2020-03-11 20:08
> I would like to work on this issue. Could you please assign this to me?

Go ahead! :)

**Comment by coderwassananmol** [comment] 2020-03-17 13:36
@poojasrinivass Any update?

**Comment by Parikshit-Hooda** [comment] 2020-03-19 06:03
I think this is abandoned by pooja. will assign to someone else, if a situation arises.

**Comment by poojasrinivass** [comment] 2020-03-19 09:37
Sorry for the delay. I am working on it. But I will need a little more time since I am learning as I work. You can assign it to someone else if an extension is not possible.

**Comment by Parikshit-Hooda** [comment] 2020-03-19 15:39
@poojasrinivass you can keep working on this issue. i am going to unassing you though so that others can attempt this issue, as well.

**Comment by BhuwanChandra** [comment] 2020-03-19 18:14
@coderwassananmol I would like to work on this issue. please assign this to me.

**Comment by Xtremilicious** [comment] 2020-03-22 10:45
@coderwassananmol @Parikshit-Hooda I would like to tackle this problem :) I'm really passionate about design.

**Comment by robot-with-feelings** [comment] 2020-03-22 13:49
If the issue is still open, I'd like to work on this if you want it to be solved using css.

**Comment by coderwassananmol** [comment] 2020-03-22 16:27
Hi guys, feel free to submit a PR! You may collaborate if you want to.

**Comment by Xtremilicious** [comment] 2020-03-23 15:14
@coderwassananmol Kindly assign each one of us a particular component, or else there would be overlapping in our work.

**Comment by coderwassananmol** [comment] 2020-03-23 20:14
@Xtremilicious You can work on the home page design.
@robot-with-feelings You can work on the header and footer design. You can also take up design for queue.
@BhuwanChandra You can take up the stats page.

**Comment by Xtremilicious** [comment] 2020-03-23 21:38
Got it!

**Comment by Xtremilicious** [comment] 2020-03-24 19:33
@Parikshit-Hooda kindly re-open this issue since this is for a complete redesign for BUB.

**Comment by Xtremilicious** [comment] 2020-03-25 06:22
@coderwassananmol kindly re-open this issue

**Closed** 2020-03-27 19:22 UTC
Labels: Design, gssoc20, hard, help wanted
